version: '3.8'

volumes:
  db:
    name: db
  django:
    name: django
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/django
      o: bind
  cert:
    name: cert
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/cert
      o: bind

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    depends_on:
      - website
    ports:
    - "443:443"
    volumes:
      - django:/website/
      - cert:/cert/
    env_file:
      - .env
    # restart: always
    tty: true
    networks:
      - network

  website:
   build:
     context: ./requirements/django-backend
     dockerfile: Dockerfile
   image: website
   container_name: website
   depends_on:
     - postgres
     - openssl-cert
     - redis
  #  ports:
  #   - "443:443"
   volumes:
     - django:/website/
     - cert:/cert/
   env_file:
     - .env
   # restart: always
   tty: true
   networks:
     - network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
     - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    # restart: always
    tty: true
    networks:
      - network

  openssl-cert:
    build:
      context: ./requirements/openssl-cert
      dockerfile: Dockerfile
    image: cert
    container_name: cert
    volumes:
     - cert:/cert/
    tty: true

  redis:
    image: redis:latest
    container_name: redis
    ports:
     - '6379:6379'
    tty: true
    networks:
      - network

networks:
  network:
    name: django-network
    driver: bridge